
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/nodejs/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Users/B760M/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/B760M/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/B760M/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/B760M/AppData/Roaming/npm/"
      - "C:/Users/B760M/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/MinGW/bin/"
      - "C:/Users/B760M/.dotnet/tools/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/ninja/win/x64/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/mingw32-make.exe.com"
    found: "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/mingw32-make.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin\\mingw\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.6.7-hotspot\\bin"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Users\\B760M\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\B760M\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\B760M\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\B760M\\AppData\\Roaming\\npm"
        - "C:\\Users\\B760M\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\MinGW\\bin"
        - "C:\\MinGW\\bin"
        - "C:\\Users\\B760M\\.dotnet\\tools"
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin"
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin\\ninja\\win\\x64"
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/share/cmake-4.1/Modules/FindGit.cmake:86 (find_program)"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/share/cmake-4.1/Modules/ExternalProject/shared_internal_commands.cmake:926 (find_package)"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/share/cmake-4.1/Modules/ExternalProject.cmake:3080 (_ep_add_download_command)"
      - "CMakeLists.txt:7 (ExternalProject_Add)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git.cmd"
      - "git"
    candidate_directories:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/nodejs/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Users/B760M/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/B760M/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/B760M/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/B760M/AppData/Roaming/npm/"
      - "C:/Users/B760M/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/MinGW/bin/"
      - "C:/Users/B760M/.dotnet/tools/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/ninja/win/x64/"
      - "C:/Program Files/bin/"
      - "C:/Program Files/sbin/"
      - "C:/Program Files/"
      - "C:/Program Files (x86)/bin/"
      - "C:/Program Files (x86)/sbin/"
      - "C:/Program Files (x86)/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/bin/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/sbin/"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/"
      - "C:/Program Files (x86)/googletest-download/bin/"
      - "C:/Program Files (x86)/googletest-download/sbin/"
      - "C:/Program Files (x86)/googletest-download/"
      - "C:/Users/B760M/AppData/Local/Atlassian/SourceTree/git_local/bin/"
    searched_directories:
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git.cmd"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git.cmd.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git.cmd.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git.cmd"
      - "C:/Windows/System32/git.cmd.com"
      - "C:/Windows/System32/git.cmd.exe"
      - "C:/Windows/System32/git.cmd"
      - "C:/Windows/git.cmd.com"
      - "C:/Windows/git.cmd.exe"
      - "C:/Windows/git.cmd"
      - "C:/Windows/System32/wbem/git.cmd.com"
      - "C:/Windows/System32/wbem/git.cmd.exe"
      - "C:/Windows/System32/wbem/git.cmd"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd"
      - "C:/Windows/System32/OpenSSH/git.cmd.com"
      - "C:/Windows/System32/OpenSSH/git.cmd.exe"
      - "C:/Windows/System32/OpenSSH/git.cmd"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git.cmd.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git.cmd.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git.cmd"
      - "C:/Program Files/nodejs/git.cmd.com"
      - "C:/Program Files/nodejs/git.cmd.exe"
      - "C:/Program Files/nodejs/git.cmd"
      - "C:/ProgramData/chocolatey/bin/git.cmd.com"
      - "C:/ProgramData/chocolatey/bin/git.cmd.exe"
      - "C:/ProgramData/chocolatey/bin/git.cmd"
      - "C:/Program Files/Git/cmd/git.cmd.com"
      - "C:/Program Files/Git/cmd/git.cmd.exe"
      - "C:/Program Files/Git/cmd/git.cmd"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/git.cmd.com"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/git.cmd.exe"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/git.cmd"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/git.cmd.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/git.cmd.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/git.cmd"
      - "C:/Program Files/dotnet/git.cmd.com"
      - "C:/Program Files/dotnet/git.cmd.exe"
      - "C:/Program Files/dotnet/git.cmd"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/git.cmd.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/git.cmd.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/git.cmd"
      - "C:/Users/B760M/AppData/Local/Programs/Python/Launcher/git.cmd.com"
      - "C:/Users/B760M/AppData/Local/Programs/Python/Launcher/git.cmd.exe"
      - "C:/Users/B760M/AppData/Local/Programs/Python/Launcher/git.cmd"
      - "C:/Users/B760M/AppData/Local/Microsoft/WindowsApps/git.cmd.com"
      - "C:/Users/B760M/AppData/Local/Microsoft/WindowsApps/git.cmd.exe"
      - "C:/Users/B760M/AppData/Local/Microsoft/WindowsApps/git.cmd"
      - "C:/Users/B760M/AppData/Local/GitHubDesktop/bin/git.cmd.com"
      - "C:/Users/B760M/AppData/Local/GitHubDesktop/bin/git.cmd.exe"
      - "C:/Users/B760M/AppData/Local/GitHubDesktop/bin/git.cmd"
      - "C:/Users/B760M/AppData/Roaming/npm/git.cmd.com"
      - "C:/Users/B760M/AppData/Roaming/npm/git.cmd.exe"
      - "C:/Users/B760M/AppData/Roaming/npm/git.cmd"
      - "C:/Users/B760M/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd.com"
      - "C:/Users/B760M/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd.exe"
      - "C:/Users/B760M/AppData/Local/Programs/Microsoft VS Code/bin/git.cmd"
      - "C:/MinGW/bin/git.cmd.com"
      - "C:/MinGW/bin/git.cmd.exe"
      - "C:/MinGW/bin/git.cmd"
      - "C:/Users/B760M/.dotnet/tools/git.cmd.com"
      - "C:/Users/B760M/.dotnet/tools/git.cmd.exe"
      - "C:/Users/B760M/.dotnet/tools/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/ninja/win/x64/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/ninja/win/x64/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/ninja/win/x64/git.cmd"
      - "C:/Program Files/bin/git.cmd.com"
      - "C:/Program Files/bin/git.cmd.exe"
      - "C:/Program Files/bin/git.cmd"
      - "C:/Program Files/sbin/git.cmd.com"
      - "C:/Program Files/sbin/git.cmd.exe"
      - "C:/Program Files/sbin/git.cmd"
      - "C:/Program Files/git.cmd.com"
      - "C:/Program Files/git.cmd.exe"
      - "C:/Program Files/git.cmd"
      - "C:/Program Files (x86)/bin/git.cmd.com"
      - "C:/Program Files (x86)/bin/git.cmd.exe"
      - "C:/Program Files (x86)/bin/git.cmd"
      - "C:/Program Files (x86)/sbin/git.cmd.com"
      - "C:/Program Files (x86)/sbin/git.cmd.exe"
      - "C:/Program Files (x86)/sbin/git.cmd"
      - "C:/Program Files (x86)/git.cmd.com"
      - "C:/Program Files (x86)/git.cmd.exe"
      - "C:/Program Files (x86)/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/bin/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/bin/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/bin/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/sbin/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/sbin/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/sbin/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/git.cmd.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/git.cmd.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64/git.cmd"
      - "C:/Program Files (x86)/googletest-download/bin/git.cmd.com"
      - "C:/Program Files (x86)/googletest-download/bin/git.cmd.exe"
      - "C:/Program Files (x86)/googletest-download/bin/git.cmd"
      - "C:/Program Files (x86)/googletest-download/sbin/git.cmd.com"
      - "C:/Program Files (x86)/googletest-download/sbin/git.cmd.exe"
      - "C:/Program Files (x86)/googletest-download/sbin/git.cmd"
      - "C:/Program Files (x86)/googletest-download/git.cmd.com"
      - "C:/Program Files (x86)/googletest-download/git.cmd.exe"
      - "C:/Program Files (x86)/googletest-download/git.cmd"
      - "C:/Users/B760M/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.com"
      - "C:/Users/B760M/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.exe"
      - "C:/Users/B760M/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git.com"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git.exe"
      - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/mingw/bin/git"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot/bin/git"
      - "C:/Windows/System32/git.com"
      - "C:/Windows/System32/git.exe"
      - "C:/Windows/System32/git"
      - "C:/Windows/git.com"
      - "C:/Windows/git.exe"
      - "C:/Windows/git"
      - "C:/Windows/System32/wbem/git.com"
      - "C:/Windows/System32/wbem/git.exe"
      - "C:/Windows/System32/wbem/git"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git"
      - "C:/Windows/System32/OpenSSH/git.com"
      - "C:/Windows/System32/OpenSSH/git.exe"
      - "C:/Windows/System32/OpenSSH/git"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/git"
      - "C:/Program Files/nodejs/git.com"
      - "C:/Program Files/nodejs/git.exe"
      - "C:/Program Files/nodejs/git"
      - "C:/ProgramData/chocolatey/bin/git.com"
      - "C:/ProgramData/chocolatey/bin/git.exe"
      - "C:/ProgramData/chocolatey/bin/git"
      - "C:/Program Files/Git/cmd/git.com"
    found: "C:/Program Files/Git/cmd/git.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin\\mingw\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.6.7-hotspot\\bin"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Users\\B760M\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\B760M\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\B760M\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\B760M\\AppData\\Roaming\\npm"
        - "C:\\Users\\B760M\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\MinGW\\bin"
        - "C:\\MinGW\\bin"
        - "C:\\Users\\B760M\\.dotnet\\tools"
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin"
        - "C:\\Program Files\\JetBrains\\CLion 2025.3.2\\bin\\ninja\\win\\x64"
      CMAKE_INSTALL_PREFIX: "C:/Program Files (x86)/googletest-download"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/Program Files/JetBrains/CLion 2025.3.2/bin/cmake/win/x64"
        - "C:/Program Files (x86)/googletest-download"
...
